# permissions for end users to view rbacreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbacreport-viewer-role
rules:
- apiGroups:
  - rbac.samueltorr.es
  resources:
  - rbacreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.samueltorr.es
  resources:
  - rbacreports/status
  verbs:
  - get
