{{- if .Values.webhook.certManager.enabled -}}
{{- if .Values.webhook.certManager.useSelfSignedIssuer -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  labels:
    {{- include "rbak.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "rbak.fullname" . }}-cert
  labels:
    {{- include "rbak.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "rbak.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "rbak.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
{{- if .Values.webhook.certManager.useSelfSignedIssuer }}
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
{{- else }}
  issuerRef:
    {{- toYaml .Values.webhook.certManager.issuerRef | nindent 4 }}
{{- end }}
  secretName: {{ include "rbak.fullname" . }}-webhook-server-cert
{{- end }}