# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rbak.fullname" . }}-leader-election-role
  labels:
    {{- include "rbak.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rbak.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "rbak.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rbak.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "rbak.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
# permissions for end users to edit rbacreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbacreport-editor-role
  labels:
    {{- include "rbak.labels" . | nindent 4 }}
rules:
- apiGroups:
  - rbac.samueltorr.es
  resources:
  - rbacreports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.samueltorr.es
  resources:
  - rbacreports/status
  verbs:
  - get
---
# permissions for end users to view rbacreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbacreport-viewer-role
  labels:
    {{- include "rbak.labels" . | nindent 4 }}
rules:
- apiGroups:
  - rbac.samueltorr.es
  resources:
  - rbacreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.samueltorr.es
  resources:
  - rbacreports/status
  verbs:
  - get
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rbak.fullname" . }}-role
  labels:
    {{- include "rbak.labels" . | nindent 4 }}
rules:
- apiGroups:
  - rbac.samueltorr.es
  resources:
  - rbacreports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.samueltorr.es
  resources:
  - rbacreports/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rbak.fullname" . }}-rolebinding
  labels:
    {{- include "rbak.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rbak.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "rbak.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
